//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesProject.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class general {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal general() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoursesProject.Resourses.general", typeof(general).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to cart.
        /// </summary>
        public static string lblAddTocart {
            get {
                return ResourceManager.GetString("lblAddTocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string lblArabic {
            get {
                return ResourceManager.GetString("lblArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our best courses.
        /// </summary>
        public static string lblBrowseOurBestCourses {
            get {
                return ResourceManager.GetString("lblBrowseOurBestCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy now.
        /// </summary>
        public static string lblbuyNow {
            get {
                return ResourceManager.GetString("lblbuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check out.
        /// </summary>
        public static string lblcheckout {
            get {
                return ResourceManager.GetString("lblcheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue shopping.
        /// </summary>
        public static string lblcontinueshopping {
            get {
                return ResourceManager.GetString("lblcontinueshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string lblCourseName {
            get {
                return ResourceManager.GetString("lblCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string lblCourses {
            get {
                return ResourceManager.GetString("lblCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A Account.
        /// </summary>
        public static string lblCreateAccount {
            get {
                return ResourceManager.GetString("lblCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        public static string lblDollar {
            get {
                return ResourceManager.GetString("lblDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGY.
        /// </summary>
        public static string lblEgy {
            get {
                return ResourceManager.GetString("lblEgy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string lblFree {
            get {
                return ResourceManager.GetString("lblFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string lblHomePage {
            get {
                return ResourceManager.GetString("lblHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructor.
        /// </summary>
        public static string lblInstructor {
            get {
                return ResourceManager.GetString("lblInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        public static string lblLectures {
            get {
                return ResourceManager.GetString("lblLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string lbllogin {
            get {
                return ResourceManager.GetString("lbllogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string lblMyAccount {
            get {
                return ResourceManager.GetString("lblMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my account.
        /// </summary>
        public static string lblMyAcount {
            get {
                return ResourceManager.GetString("lblMyAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        public static string lblproduct {
            get {
                return ResourceManager.GetString("lblproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product details.
        /// </summary>
        public static string lblproductdetails {
            get {
                return ResourceManager.GetString("lblproductdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال سعودي.
        /// </summary>
        public static string lblReal {
            get {
                return ResourceManager.GetString("lblReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roll now.
        /// </summary>
        public static string lblROLLNOW {
            get {
                return ResourceManager.GetString("lblROLLNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        public static string lblSkillLevel {
            get {
                return ResourceManager.GetString("lblSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string lblTime {
            get {
                return ResourceManager.GetString("lblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string lblVideo {
            get {
                return ResourceManager.GetString("lblVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shop.
        /// </summary>
        public static string lblWorkShop {
            get {
                return ResourceManager.GetString("lblWorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Review.
        /// </summary>
        public static string lblWriteReview {
            get {
                return ResourceManager.GetString("lblWriteReview", resourceCulture);
            }
        }
    }
}
