//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domains.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domains.Resources.ResMessage", typeof(ResMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure?.
        /// </summary>
        public static string MsgAreYouSure {
            get {
                return ResourceManager.GetString("MsgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter Arabic short description.
        /// </summary>
        public static string MsgArShortDescription {
            get {
                return ResourceManager.GetString("MsgArShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter ArabicTitle.
        /// </summary>
        public static string MsgArTitle {
            get {
                return ResourceManager.GetString("MsgArTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MsgCancel {
            get {
                return ResourceManager.GetString("MsgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter category name.
        /// </summary>
        public static string MsgCategoryName {
            get {
                return ResourceManager.GetString("MsgCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter company name.
        /// </summary>
        public static string MsgCompany {
            get {
                return ResourceManager.GetString("MsgCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not deleted.
        /// </summary>
        public static string MsgDeleteError {
            get {
                return ResourceManager.GetString("MsgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter description.
        /// </summary>
        public static string MsgDescription {
            get {
                return ResourceManager.GetString("MsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter education name.
        /// </summary>
        public static string MsgEducationName {
            get {
                return ResourceManager.GetString("MsgEducationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter email.
        /// </summary>
        public static string MsgEmail {
            get {
                return ResourceManager.GetString("MsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter employer name.
        /// </summary>
        public static string MsgEmployerName {
            get {
                return ResourceManager.GetString("MsgEmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter end date .
        /// </summary>
        public static string MsgEndDate {
            get {
                return ResourceManager.GetString("MsgEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter Engilsh short description.
        /// </summary>
        public static string MsgEnShortDescription {
            get {
                return ResourceManager.GetString("MsgEnShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter English Title.
        /// </summary>
        public static string MsgEnTitle {
            get {
                return ResourceManager.GetString("MsgEnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter expiration date.
        /// </summary>
        public static string MsgExpirationDate {
            get {
                return ResourceManager.GetString("MsgExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only JPG, JPEG, PNG, and GIF files are allowed.
        /// </summary>
        public static string MsgExtentionError {
            get {
                return ResourceManager.GetString("MsgExtentionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter firt name.
        /// </summary>
        public static string MsgFirstName {
            get {
                return ResourceManager.GetString("MsgFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select an image.
        /// </summary>
        public static string MsgImage {
            get {
                return ResourceManager.GetString("MsgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Extention.
        /// </summary>
        public static string MsgInVaildExtention {
            get {
                return ResourceManager.GetString("MsgInVaildExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string MsgInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("MsgInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Size.
        /// </summary>
        public static string MsgInvalidSize {
            get {
                return ResourceManager.GetString("MsgInvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter last name.
        /// </summary>
        public static string MsgLastName {
            get {
                return ResourceManager.GetString("MsgLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter luanguge name.
        /// </summary>
        public static string MsgLuangugeName {
            get {
                return ResourceManager.GetString("MsgLuangugeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MsgOK {
            get {
                return ResourceManager.GetString("MsgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter phone.
        /// </summary>
        public static string MsgPhone {
            get {
                return ResourceManager.GetString("MsgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation failed.
        /// </summary>
        public static string MsgSaveError {
            get {
                return ResourceManager.GetString("MsgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size exceeds the maximum allowed size (10 MB).
        /// </summary>
        public static string MsgSizeError {
            get {
                return ResourceManager.GetString("MsgSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter skill name.
        /// </summary>
        public static string MsgSkillName {
            get {
                return ResourceManager.GetString("MsgSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter start date.
        /// </summary>
        public static string MsgStartDate {
            get {
                return ResourceManager.GetString("MsgStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter title.
        /// </summary>
        public static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid email.
        /// </summary>
        public static string MsgValidEmail {
            get {
                return ResourceManager.GetString("MsgValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter year of experience.
        /// </summary>
        public static string MsgYearOfExperience {
            get {
                return ResourceManager.GetString("MsgYearOfExperience", resourceCulture);
            }
        }
    }
}
