//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domains.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domains.Resources.ResWebSite", typeof(ResWebSite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Degree.
        /// </summary>
        public static string lblAddDegree {
            get {
                return ResourceManager.GetString("lblAddDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Experience.
        /// </summary>
        public static string lblAddExperience {
            get {
                return ResourceManager.GetString("lblAddExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Luanguge.
        /// </summary>
        public static string lblAddLuanguge {
            get {
                return ResourceManager.GetString("lblAddLuanguge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        public static string lblAddSkill {
            get {
                return ResourceManager.GetString("lblAddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string lblArabic {
            get {
                return ResourceManager.GetString("lblArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string lblArDescription {
            get {
                return ResourceManager.GetString("lblArDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Data.
        /// </summary>
        public static string lblAricleData {
            get {
                return ResourceManager.GetString("lblAricleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Requirment.
        /// </summary>
        public static string lblArRequirment {
            get {
                return ResourceManager.GetString("lblArRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Short description.
        /// </summary>
        public static string lblArShortDescription {
            get {
                return ResourceManager.GetString("lblArShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Skill.
        /// </summary>
        public static string lblArSkill {
            get {
                return ResourceManager.GetString("lblArSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string lblArticle {
            get {
                return ResourceManager.GetString("lblArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Title.
        /// </summary>
        public static string lblArTitle {
            get {
                return ResourceManager.GetString("lblArTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Website Description.
        /// </summary>
        public static string lblArWebsiteDescription {
            get {
                return ResourceManager.GetString("lblArWebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Website Name.
        /// </summary>
        public static string lblArWebsiteName {
            get {
                return ResourceManager.GetString("lblArWebsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campany Name.
        /// </summary>
        public static string lblCampanyName {
            get {
                return ResourceManager.GetString("lblCampanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string lblCandidate {
            get {
                return ResourceManager.GetString("lblCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string lblContent {
            get {
                return ResourceManager.GetString("lblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string lblCountryCode {
            get {
                return ResourceManager.GetString("lblCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string lblData {
            get {
                return ResourceManager.GetString("lblData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defualt.
        /// </summary>
        public static string lblDefualt {
            get {
                return ResourceManager.GetString("lblDefualt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string lblDirection {
            get {
                return ResourceManager.GetString("lblDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Candidate.
        /// </summary>
        public static string lblEditCandidate {
            get {
                return ResourceManager.GetString("lblEditCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditCategory.
        /// </summary>
        public static string lblEditCategory {
            get {
                return ResourceManager.GetString("lblEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit CountryCode.
        /// </summary>
        public static string lblEditCountryCode {
            get {
                return ResourceManager.GetString("lblEditCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Education.
        /// </summary>
        public static string lblEditEducation {
            get {
                return ResourceManager.GetString("lblEditEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employer.
        /// </summary>
        public static string lblEditEmployer {
            get {
                return ResourceManager.GetString("lblEditEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Experience.
        /// </summary>
        public static string lblEditExperience {
            get {
                return ResourceManager.GetString("lblEditExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job.
        /// </summary>
        public static string lblEditJob {
            get {
                return ResourceManager.GetString("lblEditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Luanguge.
        /// </summary>
        public static string lblEditLuanguge {
            get {
                return ResourceManager.GetString("lblEditLuanguge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill.
        /// </summary>
        public static string lblEditSkill {
            get {
                return ResourceManager.GetString("lblEditSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string lblEducation {
            get {
                return ResourceManager.GetString("lblEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Name.
        /// </summary>
        public static string lblEducationName {
            get {
                return ResourceManager.GetString("lblEducationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string lblEmployer {
            get {
                return ResourceManager.GetString("lblEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Name.
        /// </summary>
        public static string lblEmployerName {
            get {
                return ResourceManager.GetString("lblEmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string lblEnDescription {
            get {
                return ResourceManager.GetString("lblEnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Requirment.
        /// </summary>
        public static string lblEnRequirment {
            get {
                return ResourceManager.GetString("lblEnRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Short description.
        /// </summary>
        public static string lblEnShortDescription {
            get {
                return ResourceManager.GetString("lblEnShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Skill.
        /// </summary>
        public static string lblEnSkill {
            get {
                return ResourceManager.GetString("lblEnSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title.
        /// </summary>
        public static string lblEnTitle {
            get {
                return ResourceManager.GetString("lblEnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Website Description.
        /// </summary>
        public static string lblEnWebsiteDescription {
            get {
                return ResourceManager.GetString("lblEnWebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Website Name.
        /// </summary>
        public static string lblEnWebsiteName {
            get {
                return ResourceManager.GetString("lblEnWebsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string lblExperience {
            get {
                return ResourceManager.GetString("lblExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string lblExpirationDate {
            get {
                return ResourceManager.GetString("lblExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string lblFacebookLink {
            get {
                return ResourceManager.GetString("lblFacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu.
        /// </summary>
        public static string lblGpu {
            get {
                return ResourceManager.GetString("lblGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk.
        /// </summary>
        public static string lblHardDisk {
            get {
                return ResourceManager.GetString("lblHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instgram Link.
        /// </summary>
        public static string lblInstgramLink {
            get {
                return ResourceManager.GetString("lblInstgramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string lblItem {
            get {
                return ResourceManager.GetString("lblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        public static string lblItemCategory {
            get {
                return ResourceManager.GetString("lblItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemData.
        /// </summary>
        public static string lblItemData {
            get {
                return ResourceManager.GetString("lblItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string lblJob {
            get {
                return ResourceManager.GetString("lblJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string lblJobName {
            get {
                return ResourceManager.GetString("lblJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Request.
        /// </summary>
        public static string lblJobRequest {
            get {
                return ResourceManager.GetString("lblJobRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Panner.
        /// </summary>
        public static string lblLastPanner {
            get {
                return ResourceManager.GetString("lblLastPanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo.
        /// </summary>
        public static string lblLogo {
            get {
                return ResourceManager.GetString("lblLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLuanguge {
            get {
                return ResourceManager.GetString("lblLuanguge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luanguge Name.
        /// </summary>
        public static string lblLuangugeName {
            get {
                return ResourceManager.GetString("lblLuangugeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDescriptiuon.
        /// </summary>
        public static string lblMetaDescriptiuon {
            get {
                return ResourceManager.GetString("lblMetaDescriptiuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTags.
        /// </summary>
        public static string lblMetaTags {
            get {
                return ResourceManager.GetString("lblMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddlePanner.
        /// </summary>
        public static string lblMiddlePanner {
            get {
                return ResourceManager.GetString("lblMiddlePanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Data.
        /// </summary>
        public static string lblNewsData {
            get {
                return ResourceManager.GetString("lblNewsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string lblOrder {
            get {
                return ResourceManager.GetString("lblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os.
        /// </summary>
        public static string lblOs {
            get {
                return ResourceManager.GetString("lblOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Id.
        /// </summary>
        public static string lblOsId {
            get {
                return ResourceManager.GetString("lblOsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string lblPage {
            get {
                return ResourceManager.GetString("lblPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Data.
        /// </summary>
        public static string lblPageData {
            get {
                return ResourceManager.GetString("lblPageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string lblParentCategory {
            get {
                return ResourceManager.GetString("lblParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo Album.
        /// </summary>
        public static string lblPhotAlbum {
            get {
                return ResourceManager.GetString("lblPhotAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string lblPhoto {
            get {
                return ResourceManager.GetString("lblPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string lblProcessor {
            get {
                return ResourceManager.GetString("lblProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string lblPurchasePrice {
            get {
                return ResourceManager.GetString("lblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram Size.
        /// </summary>
        public static string lblRamSize {
            get {
                return ResourceManager.GetString("lblRamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price.
        /// </summary>
        public static string lblSalesPrice {
            get {
                return ResourceManager.GetString("lblSalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reslution.
        /// </summary>
        public static string lblScreenReslution {
            get {
                return ResourceManager.GetString("lblScreenReslution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string lblScreenSize {
            get {
                return ResourceManager.GetString("lblScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string lblService {
            get {
                return ResourceManager.GetString("lblService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Data.
        /// </summary>
        public static string lblServiceData {
            get {
                return ResourceManager.GetString("lblServiceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string lblServiceName {
            get {
                return ResourceManager.GetString("lblServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        public static string lblServiceRequest {
            get {
                return ResourceManager.GetString("lblServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string lblSetting {
            get {
                return ResourceManager.GetString("lblSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Home page.
        /// </summary>
        public static string lblShowInHomePage {
            get {
                return ResourceManager.GetString("lblShowInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string lblSkill {
            get {
                return ResourceManager.GetString("lblSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        public static string lblSkillName {
            get {
                return ResourceManager.GetString("lblSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string lblSlider {
            get {
                return ResourceManager.GetString("lblSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string lblSupplier {
            get {
                return ResourceManager.GetString("lblSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string lblSupplierName {
            get {
                return ResourceManager.GetString("lblSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Link.
        /// </summary>
        public static string lblTwitterLink {
            get {
                return ResourceManager.GetString("lblTwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup.
        /// </summary>
        public static string lblUserGroup {
            get {
                return ResourceManager.GetString("lblUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Description.
        /// </summary>
        public static string lblWebsiteDescription {
            get {
                return ResourceManager.GetString("lblWebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string lblWebsiteName {
            get {
                return ResourceManager.GetString("lblWebsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string lblWeight {
            get {
                return ResourceManager.GetString("lblWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome to admin panel.
        /// </summary>
        public static string lblWelcomeAdmin {
            get {
                return ResourceManager.GetString("lblWelcomeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Of Experience.
        /// </summary>
        public static string lblYearOfExperience {
            get {
                return ResourceManager.GetString("lblYearOfExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        public static string lblYoutubeLink {
            get {
                return ResourceManager.GetString("lblYoutubeLink", resourceCulture);
            }
        }
    }
}
